name: Echo issues
on: issues
jobs:
   test:
     runs-on: ubuntu-latest
     steps:
      - name: event details
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
         
